### ISSUE TITLE
v1.0.0 TODO List

### ISSUE THREAD

**Issue by justin808** [shakacode/webpacker-lite#3]
- [x] add CHANGELOG.md

Post V1
- [ ] [merge relevant tests](https://github.com/rails/webpacker/commit/0b1a98ffdb2a72bef88f068b5e12b05d7f7c8d6c)
- [ ] Document using different deploy directories for different node/rails env #4

**Comment by justin808** [comment]
Shipped.
